import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRATYAKSH777
 */
public class complainchecking extends javax.swing.JFrame {
 Connection con=null;
    PreparedStatement pst =null;
    ResultSet rs=null;
   public String X;
    /**
     * Creates new form complainchecking
     */
    public complainchecking() {
        initComponents();
        showuser();
        setSize(1000,730);
        setTitle("STUDENT COMPLAINT CHECKING");
    }
    public ArrayList<User> userList() 
    {ArrayList<User> usersList=new ArrayList<>();
     try
        {Class.forName("com.mysql.jdbc.Driver");
        String c="W";
        con =DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
       String query="SELECT * FROM complain WHERE complains='"+c+"'";
       Statement st=con.createStatement();
       ResultSet rs=st.executeQuery(query);
       User user;
       while(rs.next())
       {user=new User(rs.getString("complainno"),rs.getString("sid"),rs.getString("complain"),rs.getString("complains"),rs.getString("complaindate"));
         usersList.add(user);  
       }
        }
 
    
         catch (ClassNotFoundException ex) {
            Logger.getLogger(complainchecking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
         Logger.getLogger(complainchecking.class.getName()).log(Level.SEVERE, null, ex);
     }
     return usersList;
    }
    public void showuser() 
    {ArrayList<User> list= userList();
    DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
    Object[] row=new Object[4];
    for(int i=0;i<list.size();i++)
    { row[0]=list.get(i).getcomplainno();
        row[1]=list.get(i).getsid();
    row[2]=list.get(i).getcomplain();
    row[3]=list.get(i).getcomplains();
    model.addRow(row);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("COMPLAINT OF STUDENT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 210, 470, 44);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(11, 260, 960, 288);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("T-Time Needed");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(610, 590, 150, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "W", "T", "R" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(540, 560, 60, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        jButton2.setText("BACK");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(690, 659, 137, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 255, 0));
        jButton3.setText("SUBMIT");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 649, 151, 40);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COMPLAINT NUMBER", "STUDENT ID", "COMPLAINT", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 20, 961, 185);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(580, 220, 240, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Approval Status");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 560, 200, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("R-Resolved");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(610, 620, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setText("W-Waiting");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(610, 570, 100, 20);

        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\PRATYAKSH777\\Downloads\\vit1-1.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-450, -10, 1620, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        wardern obj=new wardern();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
   Connection con=null;
   PreparedStatement pst =null;
   String A=jTextArea1.getText();

 if(jTextArea1.getText().length()!=0)
 {try
   {int row=jTable1.getSelectedRow();
   String value=(jTable1.getModel().getValueAt(row, 0).toString());
    String value1=(jTable1.getModel().getValueAt(row, 1).toString());
       Class.forName("com.mysql.jdbc.Driver");
    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
    pst=con.prepareStatement("update complain SET complains= ?,complain=? where complainno='"+value+"'");
    String status;
    status=jComboBox1.getSelectedItem().toString();
      pst.setString(2, X);
    pst.setString(1, status);
pst.executeUpdate();
DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
model.setRowCount(0);
showuser();
    JOptionPane.showMessageDialog(complainchecking.this,"Updated Sucessfully!!!");
    jLabel14.setText("");
    jTextArea1.setText("");
    jComboBox1.setSelectedIndex(0);
    
   
   
    
   }    catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(studentinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
   finally{
       try{con.close();
       pst.close();
      
           
       } catch (SQLException ex) {
           Logger.getLogger(studentinfo.class.getName()).log(Level.SEVERE, null, ex);
       }
   }}
 else
  JOptionPane.showMessageDialog(complainchecking.this, "Sorry,No Student is Selected RETRY!!!","Error!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int i =jTable1.getSelectedRow();
       TableModel model=jTable1.getModel();
       jTextArea1.setText(model.getValueAt(i,2).toString());
       jLabel14.setText(model.getValueAt(i,1).toString());
      X=jTextArea1.getText();
       String status=model.getValueAt(i,3).toString();
       switch(status)
       {case"W": jComboBox1.setSelectedIndex(0);break;
       case"T": jComboBox1.setSelectedIndex(1);break;
       case"R": jComboBox1.setSelectedIndex(2);break;
       }
       
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(complainchecking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(complainchecking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(complainchecking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(complainchecking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new complainchecking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
