
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRATYAKSH777
 */
public class studentinfo extends javax.swing.JFrame {
   Connection con=null;
   PreparedStatement pst =null;
   ResultSet rs=null;
   public String Q;
   public String r,s,t,u,v;
     /**
     * Creates new form studentinfo
     */
    public studentinfo() {
        initComponents();
          setSize(1000,730);
        setTitle("STUDENT INFORMATION");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        T7 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();
        T1 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        T2 = new javax.swing.JLabel();
        B2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 649, 137, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Enter Student ID  -");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(237, 43, 230, 42);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Student Phone Number");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(237, 217, 230, 42);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Student Proctor Number");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(237, 304, 230, 42);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setText("Student Parents Number");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(237, 391, 230, 42);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Student Login Password");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 480, 230, 42);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Student Address");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(237, 565, 230, 42);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Student Name");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(237, 130, 230, 42);

        T7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T7.setAutoscrolls(false);
        T7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T7ActionPerformed(evt);
            }
        });
        getContentPane().add(T7);
        T7.setBounds(520, 565, 330, 42);

        T4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T4ActionPerformed(evt);
            }
        });
        getContentPane().add(T4);
        T4.setBounds(520, 304, 330, 42);

        T5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T5ActionPerformed(evt);
            }
        });
        getContentPane().add(T5);
        T5.setBounds(520, 391, 330, 42);

        T6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6ActionPerformed(evt);
            }
        });
        getContentPane().add(T6);
        T6.setBounds(520, 478, 330, 42);

        T1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        getContentPane().add(T1);
        T1.setBounds(520, 43, 330, 42);

        T3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T3ActionPerformed(evt);
            }
        });
        getContentPane().add(T3);
        T3.setBounds(520, 217, 330, 42);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 255, 0));
        jButton2.setText("SEARCH");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 640, 153, 49);

        T2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T2.setOpaque(true);
        getContentPane().add(T2);
        T2.setBounds(521, 130, 330, 40);

        B2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        B2.setForeground(new java.awt.Color(255, 0, 0));
        B2.setText("UPDATE");
        B2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B2.setContentAreaFilled(false);
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        getContentPane().add(B2);
        B2.setBounds(740, 640, 151, 49);

        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PRATYAKSH777\\Downloads\\vit1-1.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-450, -10, 1620, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           wardern obj=new wardern();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void T4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T4ActionPerformed

    private void T5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T5ActionPerformed

    private void T6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T6ActionPerformed

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void T3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   String sid=T1.getText();
   try
   {
    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
    pst=con.prepareStatement("select * from admin where sid=?");
    pst.setString(1,sid);
    rs=pst.executeQuery();
  if(rs.next())
    {T2.setText(rs.getString("sname"));
    T3.setText(rs.getString("sno"));
    T4.setText(rs.getString("sproctno"));
    T5.setText(rs.getString("sparentno"));
    T6.setText(rs.getString("spassword"));
    T7.setText(rs.getString("sadd"));
    Q=T1.getText();
    r=T3.getText();
    s=T4.getText();
    t=T5.getText();
    u=T6.getText();
    v=T7.getText();
    
    }
 else  {
      JOptionPane.showMessageDialog(studentinfo.this, "Sorry, Inputted  Student ID is Incorrect RETRY!!!","Value Error!", JOptionPane.ERROR_MESSAGE);
 T1.setText("");
T2.setText("");
T3.setText("");
T4.setText("");
T5.setText("");
T6.setText("");
T7.setText("");}
 
   }    catch (Exception e) {
JOptionPane.showMessageDialog(studentinfo.this, "Sorry, Inputted  Student ID is Incorrect RETRY!!!","Value Error!", JOptionPane.ERROR_MESSAGE);  
 T1.setText("");
T2.setText("");
T3.setText("");
T4.setText("");
T5.setText("");
T6.setText("");
T7.setText("");
        } 
   

    }//GEN-LAST:event_jButton2ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
   
 
    String X,Y,Z,A,B,C,D;
    D=T1.getText();
     X=T3.getText();
   Y=T4.getText();
   Z=T5.getText();
   A=T2.getText();
   B=T6.getText();
   C=T7.getText();
try
{if(X.length()==10&&Y.length()==10&&Z.length()==10&&A.length()!=0&&B.length()>=6&&C.length()!=0&&Q.contentEquals(D))
{ if(X.equals(r)&&Y.equals(s)&&Z.equals(t)&&B.equals(u)&&C.equals(v)&&D.equals(Q))
    JOptionPane.showMessageDialog(studentinfo.this, "Sorry, Inputted Data is same as Stored Data RETRY!!!","Value Error!", JOptionPane.ERROR_MESSAGE);
else
{try
   {
  
    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","mysql");
    pst=con.prepareStatement("update admin SET sname='"+T2.getText()+"',sno='"+T3.getText()+"',sproctno='"+T4.getText()+"',sadd='"+T7.getText()+"',spassword='"+T6.getText()+"',Sparentno='"+T5.getText()+"' where sid='"+T1.getText()+"'");
pst.executeUpdate();
    JOptionPane.showMessageDialog(studentinfo.this,"Updated Sucessfully!!!");
   
    
   }    catch (Exception ex) {
           JOptionPane.showMessageDialog(studentinfo.this, "Sorry, Inputted Data is Incorrect Format Error1 RETRY!!!","Value Error!", JOptionPane.ERROR_MESSAGE);
       }}
}else
   JOptionPane.showMessageDialog(studentinfo.this, "Sorry, Inputted Data is Incorrect Format Error2 RETRY!!!","Value Error!", JOptionPane.ERROR_MESSAGE);  }
   finally{
       try{con.close();
       pst.close();
      
           
       } catch (Exception ex) {
           JOptionPane.showMessageDialog(studentinfo.this, "Sorry, Inputted Data is Incorrect and it causes connection issues RETRY!!!","Value Error!", JOptionPane.ERROR_MESSAGE);
       }
   }
    }//GEN-LAST:event_B2ActionPerformed

    private void T7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B2;
    private javax.swing.JTextField T1;
    private javax.swing.JLabel T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
